name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: windows-latest  # Run on Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

      - name: Download stanctl-integration binary
        run: |
          # Download the correct binary for Windows
          curl -L https://github.com/disha-148/observability-as-code/releases/download/stanctl-configuration-v1.3.0/stanctl-integration-win.exe -o $env:USERPROFILE\stanctl-integration.exe

          # Verify the file type after download
          dir $env:USERPROFILE\stanctl-integration.exe
          
          # Test if the binary is working and print the version
          & $env:USERPROFILE\stanctl-integration.exe --version
          & $env:USERPROFILE\stanctl-integration.exe --help

      - name: Add stanctl-integration to PATH
        run: |
          echo "$env:USERPROFILE\stanctl-integration.exe" >> $env:GITHUB_PATH

      - name: Get list of changed files
        id: get-changed-files
        run: |
          git fetch --all
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $changed_files"

          # Convert list of files to a single line, space-separated
          changed_files=$(echo "$changed_files" | tr '\n' ' ')

          # Set it as an environment variable for later use
          echo "changed_files=$changed_files" >> $env:GITHUB_ENV

      - name: Lint packages
        run: |
          changed_files="${{ env.changed_files }}"
          
          # Loop over each directory and check if it has changes
          foreach ($dir in Get-ChildItem -Directory "packages\@instana-integration") {
            if (echo $changed_files | Select-String $dir.FullName) {
              Write-Output "Linting package: $dir"
              Set-Location -Path $dir.FullName
              & $env:USERPROFILE\stanctl-integration.exe lint --debug --strict-mode
              Set-Location -Path $env:OLDPWD
            } else {
              Write-Output "No changes in $dir, skipping lint"
            }
          }

