name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

      - name: Install pkg globally
        run: npm install -g pkg

      #      - name: Build stanctl-integration
      #        run: |
      #          npm run build
      #          npm run pkg
      #          mv dist/stanctl-integration-linux ~/stanctl-integration
      #          chmod +x ~/stanctl-integration
      #        working-directory: tools/integration

      - name: Download all pre-built stanctl-integration binaries
        run: |
          TAG_NAME="v1.0.0"
          echo "Downloading binaries..."
          curl -L "https://github.com/${{ github.repository }}/releases/download/${TAG_NAME}/stanctl-integration-linux" -o ~/stanctl-integration-linux
          chmod +x ~/stanctl-integration-linux
          curl -L "https://github.com/${{ github.repository }}/releases/download/${TAG_NAME}/stanctl-integration-macos" -o ~/stanctl-integration-macos
          chmod +x ~/stanctl-integration-macos
          curl -L "https://github.com/${{ github.repository }}/releases/download/${TAG_NAME}/stanctl-integration-windows.exe" -o ~/stanctl-integration-windows.exe

      - name: Add stanctl-integration to PATH
        run: echo "$HOME/stanctl-integration-linux" >> "$GITHUB_PATH"

      - name: Get list of changed files
        id: get-changed-files
        run: |
          git fetch --all
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"
          # changed_files=$(git diff --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF)
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $changed_files"

          # Convert list of files to a single line, space-separated
          changed_files=$(echo "$changed_files" | tr '\n' ' ')

          # Set it as an environment variable for later use
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Lint packages
        run: |
          changed_files="${{ env.changed_files }}"
          
          # Debug: Print the environment variable
          # echo "Changed files from environment variable: $changed_files"

          # Use the correct binary based on OS
          if [ "${{ runner.os }}" == "Linux" ]; then
            LINTER_BINARY=~/stanctl-integration-linux
          elif [ "${{ runner.os }}" == "macOS" ]; then
            LINTER_BINARY=~/stanctl-integration-macos
          elif [ "${{ runner.os }}" == "Windows" ]; then
            LINTER_BINARY=~/stanctl-integration-windows.exe
          else
            echo "Unsupported platform"
            exit 1
          fi

          # Loop over each directory and check if it has changes
          for dir in packages/@instana-integration/*; do
            if [ -d "$dir" ]; then
              if echo "$changed_files" | grep -q "$dir"; then
                echo "Linting package: $dir"
                cd "$dir"
                $LINTER_BINARY lint --debug --strict-mode
                cd -
              else
                echo "No changes in $dir, skipping lint"
              fi
            fi
          done
