name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

      - name: Download stanctl-integration binary from release
        run: |
          # Download the appropriate binary for Linux from the release
          wget https://github.com/disha-148/observability-as-code/releases/download/stanctl-configuration-v1.3.0/stanctl-integration-linux -O ~/stanctl-integration

          # Make the downloaded binary executable
          chmod +x ~/stanctl-integration

      - name: Add stanctl-integration to PATH
        run: echo "$HOME" >> "$GITHUB_PATH"

      - name: Get list of changed files
        id: get-changed-files
        run: |
          git fetch --all
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $changed_files"

          # Convert list of files to a single line, space-separated
          changed_files=$(echo "$changed_files" | tr '\n' ' ')

          # Set it as an environment variable for later use
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Debug Check the binary location
        run: |
          echo "Path to binary: $HOME/stanctl-integration"
          ls -l $HOME/stanctl-integration
          file $HOME/stanctl-integration

      - name: Debug Run the binary directly
        run: |
          echo "Running binary directly"
          $HOME/stanctl-integration || echo "Error: Failed to run the binary"
          $HOME/stanctl-integration --version || echo "Failed to get version"
          $HOME/stanctl-integration --help || echo "Failed to show help"

      - name: Lint packages
        run: |
          echo "Running lint command: $HOME/stanctl-integration lint --debug --strict-mode"
          $HOME/stanctl-integration lint --debug --strict-mode || echo "Error executing lint command. Exit code: $?"

      - name: Lint packages
        run: |
          changed_files="${{ env.changed_files }}"

          # Debug: Check the contents of the changed files
          echo "Changed files: $changed_files"

          # Loop over each directory and check if it has changes
          for dir in packages/@instana-integration/*; do
            if [ -d "$dir" ]; then
              if echo "$changed_files" | grep -q "$dir"; then
                echo "Linting package: $dir"
                cd "$dir"
                echo "Running lint command: ~/stanctl-integration lint --debug --strict-mode"
                echo ~/stanctl-integration --version
                ~/stanctl-integration lint --debug --strict-mode
                if [ $? -eq 0 ]; then
                  echo "Linting successful for $dir"
                else
                  echo "Error: Linting failed for $dir"
                fi
                cd -
              else
                echo "No changes in $dir, skipping lint"
              fi
            fi
          done

