name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/@instana-integration

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^packages/@instana-integration/')
          echo "Changed files: $CHANGED_FILES"
          echo "::set-output name=changed-files::$CHANGED_FILES"

      - name: Lint each package
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.changed-files }}"
          for file in $CHANGED_FILES; do
            PACKAGE_DIR=$(dirname "$file")
            if [ -d "$PACKAGE_DIR" ]; then
              echo "Linting package $PACKAGE_DIR"
              cd "$PACKAGE_DIR"
              if stanctl-integration lint; then
                echo "Linting passed for $PACKAGE_DIR"
              else
                echo "Linting failed for $PACKAGE_DIR"
              fi
              cd -
            fi
          done
