name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

      - name: Download stanctl-integration binary
        run: |
          curl -L https://github.com/disha-148/observability-as-code/releases/download/stanctl-configuration-v1.3.0/stanctl-integration-linux -o ~/stanctl-integration
          chmod +x ~/stanctl-integration

      - name: Add stanctl-integration to PATH
        run: echo "$HOME/stanctl-integration" >> "$GITHUB_PATH"

      - name: Get list of changed files
        id: get-changed-files
        run: |
          git fetch origin

          # Check if upstream exists, if not, add it
          if ! git remote get-url upstream &>/dev/null; then
            echo "Upstream not found, adding upstream"
            git remote add upstream https://github.com/instana/observability-as-code.git
          fi

          # Ensure we have the base and head branches from the correct remotes
          if [[ "$GITHUB_BASE_REF" == "main" && "$GITHUB_HEAD_REF" == *"test-environment"* ]]; then
            # Same repo PR (same fork)
            git fetch origin $GITHUB_BASE_REF
            git fetch origin $GITHUB_HEAD_REF
          else
            # Cross-repo PR (fork to upstream)
            git fetch upstream $GITHUB_BASE_REF
            git fetch origin $GITHUB_HEAD_REF
          fi

          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"

          # Make sure the branches are valid before proceeding with the diff
          git show origin/$GITHUB_HEAD_REF || { echo "Head branch not found"; exit 1; }
          git show origin/$GITHUB_BASE_REF || { echo "Base branch not found"; exit 1; }

          # Fetch all remote refs (including remote refs that may not have been fetched)
          git fetch --all

          # Compare base branch (target branch) with head branch (source branch)
          changed_files=$(git diff --name-only origin/$GITHUB_HEAD_REF..origin/$GITHUB_BASE_REF)
          echo "Changed files: $changed_files"

          # Convert list of files to a single line, space-separated
          changed_files=$(echo "$changed_files" | tr '\n' ' ')

          # Set it as an environment variable for later use
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Verify base and head SHAs
        run: |
          git show ${{ github.event.pull_request.base.sha }}
          git show ${{ github.event.pull_request.head.sha }}

      - name: Lint packages
        run: |
          changed_files="${{ env.changed_files }}"
          
          # Loop over each directory and check if it has changes
          for dir in packages/@instana-integration/*; do
            if [ -d "$dir" ]; then
              if echo "$changed_files" | grep -q "$dir"; then
                echo "Linting package: $dir"
                cd "$dir"
                ~/stanctl-integration lint --debug --strict-mode
                cd -
              else
                echo "No changes in $dir, skipping lint"
              fi
            fi
          done