name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build stanctl-integration
        run: |
          npm run build
          npm run pkg
          mv dist/stanctl-integration-linux ~/stanctl-integration
          chmod +x ~/stanctl-integration
        working-directory: tools/integration

      - name: Add stanctl-integration to PATH
        run: echo "$HOME/stanctl-integration" >> "$GITHUB_PATH"

      - name: Get list of changed files
        id: get-changed-files
        run: |
          # Get a list of files changed in the PR against the main branch
          git fetch origin main
          changed_files=$(git diff --name-only origin/main...HEAD)
          echo "Changed files: $changed_files"
          echo "::set-output name=changed_files::$changed_files"

      - name: Lint only changed packages
        run: |
          changed_files="${{ steps.get-changed-files.outputs.changed_files }}"
          # Loop over each directory and check if it has changes
          for dir in packages/@instana-integration/*; do
            if [ -d "$dir" ]; then
              # Check if any file in the package directory has changed
              if echo "$changed_files" | grep -q "^$dir/"; then
                echo "Linting package: $dir"
                cd "$dir"
                echo "Current directory: $(pwd)"
                ~/stanctl-integration lint --debug
                cd -
              else
                echo "No changes in $dir, skipping lint"
              fi
            fi
          done
