name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build stanctl-integration
        run: |
          npm run build
          npm run pkg
          mv dist/stanctl-integration-linux ~/stanctl-integration
          chmod +x ~/stanctl-integration
        working-directory: tools/integration

      - name: Add stanctl-integration to PATH
        run: echo "$HOME/stanctl-integration" >> "$GITHUB_PATH"

      - name: Get list of changed files
        id: get-changed-files
        run: |
          changed_files=$(git diff --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF)
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Lint only changed packages
        run: |
          changed_files="${{ env.changed_files }}"
          for dir in packages/@instana-integration/*; do
            if [ -d "$dir" ] && echo "$changed_files" | grep -q "$dir"; then
              echo "Linting package: $dir"
              cd "$dir"
              ~/stanctl-integration lint --debug
              cd -
            else
              echo "No changes in $dir, skipping lint"
            fi
          done
