name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Build stanctl-integration
        run: |
          npm run build
          npm run pkg
          mv dist/stanctl-integration-linux ~/stanctl-integration
          chmod +x ~/stanctl-integration
        working-directory: tools/integration

      - name: Add stanctl-integration to PATH
        run: echo "$HOME/stanctl-integration" >> "$GITHUB_PATH"

      - name: Get list of changed files
        id: get-changed-files
        run: |
          # Fetch all branches to ensure we have the latest data
          git fetch --all
          
          # Check the branches being compared
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"

          # Get the list of changed files between the PR base and head branches
          # changed_files=$(git diff --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF)
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})


          # Debug: Print the list of changed files
          echo "Changed files: $changed_files"

          # Convert list of files to a single line, space-separated
          changed_files=$(echo "$changed_files" | tr '\n' ' ')

          # Set it as an environment variable for later use
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Lint only changed packages
        run: |
          # Read the list of changed files from the environment variable
          changed_files="${{ env.changed_files }}"
          
          # Debug: Print the environment variable
          echo "Changed files from environment variable: $changed_files"

          # Loop over each directory and check if it has changes
          for dir in packages/@instana-integration/*; do
            if [ -d "$dir" ]; then
              # Check if any file in the package directory has changed
              # Only check for files within the package directory
              if echo "$changed_files" | grep -q "$dir"; then
                echo "Linting package: $dir"
                cd "$dir"
                echo "Current directory: $(pwd)"
                ~/stanctl-integration lint --debug
                cd -
              else
                echo "No changes in $dir, skipping lint"
              fi
            fi
          done
