name: Lint Packages

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  lint-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies for tools/integration
        run: npm ci
        working-directory: tools/integration

#      - name: Download stanctl-configuration binary (Linux)
#        run: |
#          wget https://github.com/instana/observability-as-code/releases/download/stanctl-configuration-v1.2.0/stanctl-configuration-linux -O ~/stanctl-configuration
#          wget https://github.com/instana/observability-as-code/releases/download/stanctl-configuration-v1.2.0/stanctl-integration-linux
#          chmod +x ~/stanctl-configuration

      - name: Download stanctl-configuration binary (Linux)
        run: |
          # Correct URL for downloading the binary file directly
          wget https://github.com/instana/observability-as-code/releases/download/stanctl-configuration-v1.2.0/stanctl-integration-linux -O ~/stanctl-integration-linux

          # Make the downloaded binary executable
          chmod +x ~/stanctl-integration-linux

      - name: Add stanctl-configuration to PATH
        run: echo "$HOME" >> "$GITHUB_PATH"

      - name: Get list of changed files
        id: get-changed-files
        run: |
          git fetch --all
          echo "Base branch: $GITHUB_BASE_REF"
          echo "Head branch: $GITHUB_HEAD_REF"
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "Changed files: $changed_files"

          # Convert list of files to a single line, space-separated
          changed_files=$(echo "$changed_files" | tr '\n' ' ')

          # Set it as an environment variable for later use
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Check if linting binary exists and is executable
        run: |
          if [ ! -f $HOME/stanctl-integration-linux ]; then
            echo "Error: Linting binary not found!"
            exit 1
          fi
          if [ ! -x $HOME/stanctl-integration-linux ]; then
            echo "Error: Linting binary is not executable!"
            exit 1
          fi
          echo "Linting binary is ready!"

      - name: Lint packages
        run: |
          changed_files="${{ env.changed_files }}"

          # Loop over all directories in packages/@instana-integration/
          for dir in packages/@instana-integration/*; do
            if [ -d "$dir" ]; then
              # Check if any changed file is inside this directory
              echo "Checking directory: $dir"
              echo "Changed files: $changed_files"

              # Loop over each changed file and check if it's in the current directory
              for file in $(echo "$changed_files" | tr ' ' '\n'); do
                if [[ "$file" == $dir/* ]]; then
                  echo "Linting package: $dir"
                  cd "$dir"
                  ~/stanctl-integration-linux lint --debug --strict-mode
                  cd -
                  break
                fi
              done
            fi
          done



